name: what_where_when_master
description: An application for master of "What? Where? When?" game.

publish_to: "none"

version: 0.5.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.5
  cupertino_icons: ^1.0.0
  firebase_analytics: ^9.0.4
  firebase_auth: ^3.3.4
  firebase_core: ^1.10.6
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  flutter_localizations:
    sdk: flutter
  innim_lib:
    git:
      url: http://git.innim.ru:1414/flutter/plugins/
      path: packages/innim_lib
      ref: innim_lib/0.4
  innim_ui:
    git:
      url: http://git.innim.ru:1414/flutter/plugins/
      path: packages/ui/innim_ui
      ref: innim_ui/0.5
  intl: ^0.17.0
  json_annotation: ^4.4.0
  multiple_localization: ^0.2.2
  numerus: ^1.0.2
  quiver: ^3.0.1+1
  shared_preferences: ^2.0.11

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  innim_lint: ^0.2.0
  json_serializable: ^6.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/
