name: WhatWhereWhenMaster
description: An application for master of "What? Where? When?" game.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^6.0.0
  intl: ^0.16.1
  innim_lib:
    git:
      url: http://git.innim.ru:1414/flutter/plugins/
      path: packages/innim_lib
      ref: innim_lib/0.2
  innim_ui:
    git:
      url: http://git.innim.ru:1414/flutter/plugins/
      path: packages/ui/innim_ui
      ref: innim_ui/0.2
  multiple_localization: ^0.1.0+5
  json_annotation: ^3.0.0
  numerus: ^1.0.2
  quiver: ^2.1.3
  cupertino_icons: ^1.0.0
  firebase_core: "0.5.0"
  firebase_analytics: ^6.0.1
  firebase_auth: ^0.18.1
  cloud_firestore: "^0.14.0+2"

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.9
  json_serializable: ^3.3.0
  build_runner: ^1.10.0
  pedantic: ^1.0.0

flutter:
  uses-material-design: true