name: what_where_when_master
description: An application for master of "What? Where? When?" game.

publish_to: "none"

version: 0.6.1+4

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  animator: ^3.3.0
  async: ^2.11.0
  cloud_firestore: ^4.15.8
  cupertino_icons: ^1.0.0
  dio: ^5.4.1
  equatable: ^2.0.5
  firebase_analytics: ^10.8.9
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  innim_bloc:
    hosted: http://pub.innim.ru
    version: ^1.0.2
  innim_lib:
    hosted: http://pub.innim.ru
    version: ^1.4.3
  innim_ui:
    hosted: http://pub.innim.ru
    version: ^2.3.5
  intl: ^0.18.0
  json_annotation: ^4.8.1
  multiple_localization: ^0.4.0
  numerus: ^2.2.0
  quiver: ^3.0.1+1
  shared_preferences: ^2.0.11

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  innim_lint: ^0.5.0+1
  intl_translation: ^0.18.2
  json_serializable: ^6.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/

alex:
  l10n:
    output_dir: lib/application/l10n
    source_file: lib/application/localization.dart
    translation_files_pattern: intl_{locale}.arb
    base_locale_for_abr: ru
  ci:
    enabled: false
